MotorSim:
  # Publish all joint states -----------------------------------

 joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 10

  # Position Controllers ---------------------------------------

 Shaft_position_controller:
  type: effort_controllers/JointPositionController
  joint: MotorJoint
  pid: {p: 1, i: 0, d: 0}
