motorsim:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  shaft_position_controller:
    type: effort_controllers/JointPositionController
    joint: motorjoint
    pid: {p: 1, i: 0.001, d: 0.001}
