MotorSim:
 joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 10
 shaft_position_controller:
  type: effort_controllers/JointPositionController
  joint: shaft
